- name: Hello world deploy
  hosts: all
  become: yes
  tasks:
    - name: Install nginx
      dnf:
        name: nginx
        state: present
    - name: Create webpage
      copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Hello World from GitHub Actions</h1>"
    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes